const sections = {
  '전체': ['kr'],
  // '신입': ['kr-newbie', 'kr-join'],
  '일상':['life', 'kr-life', 'kr-daily'],
  '도서':['book', 'kr-book', 'booksteem'],
  '글쓰기': ['kr-pen', 'kr-writing', 'pen', 'writing'],
  // '운동': ['actifit'],
  '이벤트': ['event', 'kr-event'],
  '게임':['game', 'kr-game', 'steemmonsters', 'nextcolony'],
  '맛집/음식':['tasteem', 'tasteem-kr', 'muksteem', 'food', 'kr-food'],
  // '연재': ['kr-series'],
  '여행': ['tripsteem', 'travel', 'kr-travel'],
  // '해외': ['kr-overseas'],
	'코딩/개발': ['kr-dev', 'dev'],
  '예술/디자인': ['art', 'kr-art', 'ntopaz'],
  '사진': ['photo', 'kr-photo'],
  // '블록체인': ['coinkorea'],
  // '투자': ['tooza'],
  '가즈아': ['kr-gazua'],
  '스팀코인판': ['sct']
  // '기술': [],
  // '문화': [],
  // '사업': [],
  // '정치': [],
  // '과학': [],
  // '건강': [],
  // '스타일': [],
};

export default sections;